### ISSUE TITLE
VMM backup Script fails but cant tell why?

### ISSUE THREAD

**Issue by dacootmeister** [m4r1oph/Synology-vmm-backup#1]
Hi @m4r1oph ,

First of all thank you for the script!
I tried to follow the instructions, modified paths and and create all directories but the export doesnt go anywhere in in the designated folders.
Any tips, tricks?

bash /volume1/public/Synology-vmm-backup/Synology-vmm-backup.sh
[Line 265] Not a json value: Ubuntu
[Line 295] Exec WebAPI:  api=SYNO.Virtualization.API.Guest.Action, version=1, method=shutd
{
   "error" : {
      "code" : 907
   },
   "httpd_restart" : false,
   "success" : false
}
Selected backup list:
        Ubuntu
[Sun Jun 30 07:54:38 PM CEST 2024] Starting to clone 1 VMs ...
[Sun Jun 30 07:54:38 PM CEST 2024] [Clone] Done
[Sun Jun 30 07:54:39 PM CEST 2024] Starting to export ova to the backup folder...
[Export] Progress: 0/1 [Sun Jun 30 08:10:16 PM CEST 2024] [Export] Done
mv: missing destination file operand after '/volume2/Backup/VMBackups/NoBackups'
Try 'mv --help' for more information.
cp: missing destination file operand after '/volume2/Backup/VMBackups/HyperBackup/WS.ova'
Try 'cp --help' for more information.
[Line 265] Not a json value: Ubuntu
[Line 295] Exec WebAPI:  api=SYNO.Virtualization.API.Guest.Action, version=1, method=poweron, param={"guest_name":"Ubuntu"}, runner=admin
{
   "httpd_restart" : false,
   "success" : true

**Comment by m4r1oph** [comment]
Hi! I'm a bit rusty with this script but I can try to help you. Can you send the modied script so i can see it. Thanks!

**Comment by dacootmeister** [comment]
> Hi! I'm a bit rusty with this script but I can try to help you. Can you send the modied script so i can see it. Thanks!


uhm, how do I reach you?

**Comment by m4r1oph** [comment]
You can just paste it here.

**Comment by dacootmeister** [comment]
Here goes:

#!/bin/bash

synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=shutdown runner=admin guest_name="Ubuntu"
sleep 15s

/var/packages/Virtualization/target/bin/vmm_backup_ova --dst=Backup --batch=1 --guests="Ubuntu"
mv $(find /volume2/Backup/VMBackups -maxdepth 1 -type f ! -name '.*' ! -name 'Ubuntu*') /volume2/Backup/VMBackups/NoBackups
num_backups=$(find /volume2/Backup/VMBackups -maxdepth 1 -type f ! -name '.*' | wc -l)
if [[ $num_backups -gt 3 ]]
    then
        mkdir /volume2/Backup/VMBackups/logs
        backup_old=$(find /volume2/Backup/VMBackups -maxdepth 1 -type f -printf '%T+ %p\n' | sort > /volume2/Backup/VMBackups/logs/fich.txt)
        num_lin=$(cat /volume2/Backup/VMBackups/logs/fich.txt | wc -l )
        num_old=$(($num_lin-3))
        if [[ $num_old -gt 0 ]]
            then
                num_delete=$(($num_old+1))
                cat /volume2/Backup/VMBackups/logs/fich.txt | head -n $num_old | cut -d " " -f 2 > /volume2/Backup/VMBackups/logs/del_old.txt
                num_lin=$(cat /volume2/Backup/VMBackups/volume2/Backup/VMBackups/logs/del_old.txt | wc -l )
                for i in $(seq 1 $num_lin)
                    do
                        delete=$(cat /volume2/Backup/VMBackups/logs/del_old.txt | sed -n $i'p')
                        rm $delete
                done
        fi
        rm -r /volume2/Backup/VMBackups/logs
fi

hyper_backup=$(find /volume2/Backup/VMBackups -maxdepth 1 -type f -printf '%T+ %p\n' | sort | tail -n 1 | cut -d " " -f 2)
cp $hyper_backup /volume2/Backup/VMBackups/HyperBackup/WS.ova

synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=poweron runner=admin guest_name="Ubuntu"

**Comment by m4r1oph** [comment]
I think the problem is in the names of the folders. According to the documentation, they need to have the same name as the VM. I'm not sure why, but it's probably for a specific reason.

This script needs a revision, but I can't test if the changes are working. I'm going to leave you some changes to make it easier to use, but as I mentioned, I can't really test if it's working.

**Comment by m4r1oph** [comment]
```
#!/bin/bash

# Define variables for paths and VM name
VM_NAME="Ubuntu"
SHARED_FOLDER="Backup"
BACKUP_FOLDER="/volume2/$SHARED_FOLDER/VMBackups"
DEST_FOLDER="/volume2/$SHARED_FOLDER/VMBackups/$VM_NAME"
LOGS_FOLDER="/volume2/$SHARED_FOLDER/VMBackups/logs"
HYPER_BACKUP_FOLDER="/volume2/$SHARED_FOLDER/VMBackups/HyperBackup"
NO_BACKUPS_FOLDER="/volume2/$SHARED_FOLDER/VMBackups/NoBackups"

# Shutdown the virtual machine
synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=shutdown runner=admin guest_name="$VM_NAME"
sleep 15s

# Backup the virtual machine
/var/packages/Virtualization/target/bin/vmm_backup_ova --dst=$SHARED_FOLDER --batch=1 --guests="$VM_NAME"

# Move non-VMName backup files to NoBackups directory
mv $(find $BACKUP_FOLDER -maxdepth 1 -type f ! -name '.' ! -name "$VM_NAME") $NO_BACKUPS_FOLDER

# Count the number of backup files
num_backups=$(find $BACKUP_FOLDER -maxdepth 1 -type f ! -name '.*' | wc -l)

# If there are more than 3 backup files, delete the oldest ones
if [[ $num_backups -gt 3 ]]; then
    mkdir -p $LOGS_FOLDER
    find $BACKUP_FOLDER -maxdepth 1 -type f -printf '%T+ %p\n' | sort > $LOGS_FOLDER/fich.txt

    num_lin=$(wc -l < $LOGS_FOLDER/fich.txt)
    num_old=$(($num_lin - 3))

    if [[ $num_old -gt 0 ]]; then
        num_delete=$(($num_old + 1))
        head -n $num_old $LOGS_FOLDER/fich.txt | cut -d " " -f 2 > $LOGS_FOLDER/del_old.txt

        num_lin=$(wc -l < $LOGS_FOLDER/del_old.txt)

        for i in $(seq 1 $num_lin); do
            delete=$(sed -n ${i}p $LOGS_FOLDER/del_old.txt)
            rm $delete
        done
    fi

    rm -r $LOGS_FOLDER
fi

# Copy the most recent backup to HyperBackup directory
hyper_backup=$(find $BACKUP_FOLDER -maxdepth 1 -type f -printf '%T+ %p\n' | sort | tail -n 1 | cut -d " " -f 2)
cp $hyper_backup $HYPER_BACKUP_FOLDER/WS.ova

# Power on the virtual machine
synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=poweron runner=admin guest_name="$VM_NAME"
```

**Comment by dacootmeister** [comment]
Thanks so much @m4r1oph , I will test it immediately :-D

Output:
[Line 265] Not a json value: Ubuntu
[Line 295] Exec WebAPI:  api=SYNO.Virtualization.API.Guest.Action, version=1, method=shutdown, param={"guest_name":"Ubuntu"}, runner=admin
{
   "httpd_restart" : false,
   "success" : true
}
Selected backup list:
        Ubuntu
[Mon Jul  1 12:16:44 PM CEST 2024] Starting to clone 1 VMs ...
[Mon Jul  1 12:16:44 PM CEST 2024] [Clone] Done
[Mon Jul  1 12:16:46 PM CEST 2024] Starting to export ova to the backup folder..                                                                                                                                                                                                                                             .
[Export] Progress: 0/1 [Mon Jul  1 12:31:52 PM CEST 2024] [Export] Done
mv: missing destination file operand after '/volume2/Backup/VMBackups/NoBackups'
Try 'mv --help' for more information.
cp: missing destination file operand after '/volume2/Backup/VMBackups/HyperBacku                                                                                                                                                                                                                                             p/WS.ova'
Try 'cp --help' for more information.
[Line 265] Not a json value: Ubuntu
[Line 295] Exec WebAPI:  api=SYNO.Virtualization.API.Guest.Action, version=1, me                                                                                                                                                                                                                                             thod=poweron, param={"guest_name":"Ubuntu"}, runner=admin
{
   "httpd_restart" : false,
   "success" : true
}


Besides the errors regard MV and CP operands, the script managed to create *.ova files in respective /volume2/Backup/Ubuntu folder which almost makes it useable!
Thanks so far. I will try to figure out why the MV and CP commands fail.

**Comment by dacootmeister** [comment]
@m4r1oph this part of the script doesnt get executed

# Move non-VMName backup files to NoBackups directory
mv $(find $BACKUP_FOLDER -maxdepth 1 -type f ! -name '.' ! -name "$VM_NAME") $NO_BACKUPS_FOLDER

# Count the number of backup files
num_backups=$(find $BACKUP_FOLDER -maxdepth 1 -type f ! -name '.*' | wc -l)

# If there are more than 3 backup files, delete the oldest ones
if [[ $num_backups -gt 3 ]]; then
    mkdir -p $LOGS_FOLDER
    find $BACKUP_FOLDER -maxdepth 1 -type f -printf '%T+ %p\n' | sort > $LOGS_FOLDER/fich.txt

    num_lin=$(wc -l < $LOGS_FOLDER/fich.txt)
    num_old=$(($num_lin - 3))

    if [[ $num_old -gt 0 ]]; then
        num_delete=$(($num_old + 1))
        head -n $num_old $LOGS_FOLDER/fich.txt | cut -d " " -f 2 > $LOGS_FOLDER/del_old.txt

        num_lin=$(wc -l < $LOGS_FOLDER/del_old.txt)

        for i in $(seq 1 $num_lin); do
            delete=$(sed -n ${i}p $LOGS_FOLDER/del_old.txt)
            rm $delete
        done
    fi

    rm -r $LOGS_FOLDER
fi

**Comment by m4r1oph** [comment]
Perfect! If in the future you solve it and want to do a PR, you can leave it here for anyone who has the same problem. That would be awesome.

**Comment by dacootmeister** [comment]
@m4r1oph I couldnt get the MV and CP actions working unfortunately.
Therefore I cut them out of the script and reduced it to this:

In my case it doesn't matter much as I replicate the whole backup share each night to another NAS elsewhere using Synology Snapshot Replication.


```
#!/bin/bash

# Define variables for paths and VM name
VM_NAME="CPHM"
SHARED_FOLDER="Backup"
LOGS_FOLDER="/volume2/$SHARED_FOLDER/logs"

# Shutdown the virtual machine
synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=shutdown runner=admin guest_name="$VM_NAME"
sleep 15s

# Backup the virtual machine
/var/packages/Virtualization/target/bin/vmm_backup_ova --dst=$SHARED_FOLDER --batch=1 --guests="$VM_NAME"

# Count the number of backup files
num_backups=$(find /volume2/Backup/CPHM -maxdepth 1 -type f ! -name '.*' | wc -l)

# If there are more than 3 backup files, delete the oldest ones
if [[ $num_backups -gt 3 ]]; then
    mkdir -p $LOGS_FOLDER
    find /volume2/Backup/CPHM -maxdepth 1 -type f -printf '%T+ %p\n' | sort > $LOGS_FOLDER/fich.txt

    num_lin=$(wc -l < $LOGS_FOLDER/fich.txt)
    num_old=$(($num_lin - 3))

    if [[ $num_old -gt 0 ]]; then
        num_delete=$(($num_old + 1))
        head -n $num_old $LOGS_FOLDER/fich.txt | cut -d " " -f 2 > $LOGS_FOLDER/del_old.txt

        num_lin=$(wc -l < $LOGS_FOLDER/del_old.txt)

        for i in $(seq 1 $num_lin); do
            delete=$(sed -n ${i}p $LOGS_FOLDER/del_old.txt)
            rm $delete
        done
    fi

    rm -r $LOGS_FOLDER
fi

# Power on the virtual machine
synowebapi --exec api=SYNO.Virtualization.API.Guest.Action version=1 method=poweron runner=admin guest_name="$VM_NAME"
```

**Comment by m4r1oph** [comment]
It's extrange, if someday i have the opportunity i will resolve it, but for now if its working for you i'm glad.

**Comment by Percherie** [comment]
Why use code to indicate the number of retentions when this is possible natively?
This avoids the need to create a temporary log file during processing.

`/var/packages/Virtualization/target/bin/vmm_backup_ova --dst=$SHARED_FOLDER --batch=1 --guests="$VM_NAME" --retent=$NUMBER_BACKUPS`
